import React, {useState} from 'react';
import SnippetHolder from './containers/SnippetHolder.jsx';
import Input from './containers/Input.jsx';

const App = () => {
	// TODO: Change setJSON to setTarget
	let [target, setJSON] = useState('');
	let [badWordList, setBadWordList] = useState([]);
	let [instanceName, setInstanceName] = useState('AutoGenerated');
	let [errorMsg, setError] = useState('');

	let snippetProps = {
		badWordList: badWordList,
		target: target,
		instanceName: instanceName
	};

	let inputProps = {
		setJSON: setJSON,
		instanceName: instanceName,
		setBadWordList: setBadWordList,
		setError: setError
	};

	return (
		<div className="container main">
			<div className="header">
				<h1>THIS SET IS THE HEADER</h1>
				<p>{errorMsg} {errorMsg && ' Please try again!'}</p>
			</div>
			<div>
				<p>Name the instance:</p>
				<p>
					<input
						type="text"
						onChange={(e) => {
							if (!e || !e.target || !e.target.value) {
								console.error("Failed to read event:");
								console.error(e);
								setError(`Failed in Event: ${e}`)
								return
							}

							setInstanceName(e.target.value);
						}}
						defaultValue={instanceName}
					/>
				</p>
				<Input {...inputProps} />
			</div>
			<div>
				 <SnippetHolder {...snippetProps} />
			</div>
		</div>
	);
};

export default App;
